
[global_env]

[scripts]
build = { command = "cargo build", info = "Build w/ debug symbols", env = { RUST_LOG = "info" } }
db = { command = "docker run --rm --name pg -p 5432:5432 -e POSTGRES_PASSWORD=welcome postgres:17;", info="Start Postgres DB Docker container" }
dev = { command = "cargo run -p web-server", info = "Start a dev server" }
dev-watch = { command = "cargo watch -q -c -w crates/services/web-server/src/ -w crates/libs/ -w .cargo/ -x 'run -p web-server'", info = "Start dev server in watch mode" }
doc = { command = "cargo doc --no-deps --open", info = "Build project documentation" }
quick = { command = "cargo run -p web-server --example quick_dev", info = "Run the quick-dev example program" }
release = { command = "cargo build --release", info = "Build project in release mode" }
test = { command = "cargo nextest run -j1", env = { RUST_LOG = "warn"}, info = "Run project tests" }
test-watch = { command = "cargo watch -q -c -x 'nextest run -j1'", env = { RUST_LOG = "warn"}, info = "Run tests in watch mode" }
