// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvKind } from "./ConvKind.d";
import type { ConvState } from "./ConvState.d";

export type Conv = { id: bigint, agent_id: bigint, owner_id: bigint, title: string | null, kind: ConvKind, state: ConvState, cid: bigint, ctime: string, mid: bigint, mtime: string, };
