// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Note: Here we derive from modql `SeaFieldValue` which implements
 *       the `From<ConvState> for sea_query::Value` and the
 *       `sea_query::value::Nullable for ConvState`
 *       See the `ConvKind` for the manual implementation.
 *
 */
export type ConvState = "Active" | "Archived";
