// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./lib_core_dbx_Error.d";

export type Error = { "EntityNotFound": { entity: string, id: bigint, } } | { "ListLimitOverMax": { max: bigint, actual: bigint, } } | "CountFail" | { "UserAlreadyExists": { username: string, } } | { "UniqueViolation": { table: string, constraint: string, } } | { "CantCreateModelManagerProvider": string } | { "Pwd": Error } | { "Dbx": Error } | { "SeaQuery": string } | { "ModqlIntoSea": string };
