// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Error = "HmacFailNewFromSlice" | "InvalidFormat" | "CannotDecodeIdent" | "CannotDecodeExp" | "SignatureNotMatching" | "ExpNotIso" | "Expired";
