// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./lib_auth_token_Error.d";
import type { CtxExtError } from "./lib_web_middleware_Error.d";

export type Error = { "type": "LoginFailUsernameNotFound" } | { "type": "LoginFailUserHasNoPwd", "data": { user_id: bigint, } } | { "type": "LoginFailPwdNotMatching", "data": { user_id: bigint, } } | { "type": "CtxExt", "data": CtxExtError } | { "type": "ReqStampNotInReqExt" } | { "type": "Model", "data": Error } | { "type": "Pwd", "data": Error } | { "type": "Token", "data": Error } | { "type": "Rpc", "data": Error } | { "type": "RpcLibRpc", "data": Error } | { "type": "RpcHandlerErrorUnhandled", "data": string } | { "type": "RpcRouter", "data": { method: string, } } | { "type": "SerdeJson", "data": string };
