// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./lib_core_Error.d";

export type Error = { "Model": Error } | { "SerdeJson": string };
